




// @function 取得快線(Fast Line)
export method _getK_(_KDJ_ this) =>
    float retValue = 00.00
    //////////////////////////////////////////////////
    float _rsv_ = _Calc_RSV_(this._source_, this._signal_length_)
    //////////////////////////////////////////////////
    retValue := _Calc_K_(_rsv_, this._fast_length_)
    //////////////////////////////////////////////////
    retValue