




export method _getPositiveDI_(_DMI_ this) =>
    float retValue = 00.00
    ////////////////////////////////////////////////////////////
    float dm = _Calc_DM_(_Positive_Negative_._Positive_)
    float tr = _Calc_TR_(                              )
    ////////////////////////////////////////////////////////////
    float adm = _Calc_DM_AVG_(dm, this._di_length_)
    float atr = _Calc_TR_AVG_(tr, this._di_length_)
    ////////////////////////////////////////////////////////////
    retValue := _Calc_DI_(adm, atr)
    ////////////////////////////////////////////////////////////
    retValue